# -*- coding: utf-8 -*-
"""PdfExtraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NFUyVNVrjSnulxvAzHgKgsLtgnOg66FI
"""

import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import tabula
import glob
import os

crisil_files = os.listdir('C:\\Users\\g_abh\\Desktop\\crisil_pdfs')
icra_files = os.listdir('C:\\Users\\g_abh\\Desktop\\icra_pdfs')
print(crisil_files, icra_files)

df = pd.read_excel("Book3.xlsx")

print(df)

df_copy=df.copy()

crisil_df_list=[]
for file in crisil_files:
  df_pdf = tabula.read_pdf(file, pages=1, lattice=True)
  new_header = df_pdf[0].iloc[0]
  df_pdf[0] = df_pdf[0][1:] 
  df_pdf[0].columns = new_header 
  df_filtered=df_pdf[0]
  df_filtered.columns = df_filtered.columns.str.replace("\r", " ")
  print(df_filtered)
  crisil_df_list.append(df_filtered)

crisil_large_df = pd.concat(crisil_df_list, ignore_index=True)

print(crisil_large_df)

icra_df_list=[]
for file in icra_files:
  df_pdf = tabula.read_pdf(file, pages=[2], lattice=True)
  new_header = df_pdf[0].iloc[0]
  df_pdf[0] = df_pdf[0][1:] 
  df_pdf[0].columns = new_header 
  df_filtered=df_pdf[0]
  df_filtered.columns = ['ISIN No','Series','Date of Allotment','Maturity Date','Reference Asset','Face Value (in Rs.)','Valuation*']
  print(df_filtered)
  icra_df_list.append(df_filtered)

icra_large_df = pd.concat(icra_df_list, ignore_index=True)
icra_large_df.replace("\r", " ")
icra_large_df

df_price_crisil=crisil_large_df[["ISIN Code", "Valuation per Rs 100 Face Value"]]
df_price_crisil.columns=["ISIN", "Valuation"]
df_price_icra=icra_large_df[["ISIN No", "Valuation*"]]
df_price_icra.columns=["ISIN", "Valuation"]

print(df_price_crisil)

print(df_price_icra)

df_price = pd.concat([df_price_crisil,df_price_icra], ignore_index=True)
print(df_price)

for i in df_price["ISIN"]:
  if i in df["ISIN"].values:
    print(i)
    print(df.loc[df["ISIN"]==i, "Ticker"])
    print(df_price.loc[df_price["ISIN"]==i,"Valuation"].values[0])
    df.loc[df["ISIN"]==i, "Ticker"]=(df_price.loc[df_price["ISIN"]==i,"Valuation"].values[0])

print(df)

print(df_copy)

writer = ExcelWriter('Revised_values.xlsx')
df.to_excel(writer, 'Main')
crisil_large_df.to_excel(writer, 'CRISIL')
icra_large_df.to_excel(writer, 'ICRA')
writer.save()

